Feature/bloc user auth
boostgrade/wtgt_beta pull request #30
Opened 2021-12-20 19:45 UTC by MirkoZorich

# Ссылка на задачу
Задача #12 

# Что было сделано

Проект реализации
В последствии создан bloc для модуля авторизации

Отправить с фронта событие, получить обратно данные из потока

Опиши по шагам, как проверить проделанное тобой.

# Чек-лист

- [ ] Функциональность протестирована и работает корректно
- [ ] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2021-12-21 08:27 UTC, artem-zaitsev requested changes
Описывай события и стейты, а также сам класс блока.

2021-12-21 08:27 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +* Б - stream 'need_auth' - если нужна регистрация, фронт показывает страницу регистрации
Это не ответственность AuthBloc.   AuthBloc будет проще: умеет пинять номер телефона, СМС код, события авторизации по соц.сетям, регистрации и логаута.

2021-12-21 08:27 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +* 2. Страница регистрации - может это не нужно и фронт сам даст нужную страницу?
Блок не отдает страницу. Блок отдает просто событие. Он не знает о том, как конкретно устроен UI. 
В нашем конкретном случае достаточно событий:
- загрузка, ожидание данных
- ошибка
- успех 

В успехе можно выдать результат работы с запросом/сторонним сервисом. В нашем случае это в основном работа с сервером.

2021-12-21 08:27 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +* Б - stream 'success/error' - фронт показывает главную страницу приложения
Вот примерно то же у тебя будет для пункта 2.

2022-01-11 12:58 UTC, artem-zaitsev requested changes
Стоит писать описание к классам, потому что не всегда явно из их названия что они делают.

По блоку надо сделать интеграцию с репозиторием.

2022-01-11 12:58 UTC, artem-zaitsev commented on lib/src/modules/auth/services/events/auth_event.dart
> +  final Enum type;
Тебе надо завести конкретный enum:
```
enum SocialTypes { vk, apple, google, fb }
```
например так.

И здесь уже будет 
```
SocialType type;
```

2022-01-11 12:58 UTC, artem-zaitsev commented on lib/src/modules/auth/services/states/auth_state.dart
> +class EmittedState extends AuthState {}
В чем отличие этих двух состояний? Напиши описание к классам.

2022-01-11 12:58 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +class AuthBloc extends Bloc<AuthEvent, AuthState> {
У нас уже реализован репозиторий.
Блок должен с ним взаимодействовать:
- сначала выдавать состояние загрузки
- делать запрос
- отдавать состояние успеха(или если необходимо с данными, но вроде таких кейсов нет)

2022-01-12 17:41 UTC, MirkoZorich commented
Автотетсы дают такие ошибки, не знаю как исправить

   info • The declaration '_internal' isn't referenced • lib/src/services/exceptions/server/parse_error.dart:11:13 • unused_element
   info • Avoid `print` calls in production code • lib/src/services/exceptions/server/server_exceptions.dart:15:5 • avoid_print
   info • Avoid `print` calls in production code • lib/src/services/exceptions/server/server_exceptions.dart:29:5 • avoid_print
   info • The value of the field '_errorCode' isn't used • lib/src/services/exceptions/server/server_exceptions.dart:36:13 • unused_field
   info • The value of the field '_errorCode' isn't used • lib/src/services/exceptions/server/server_exceptions.dart:52:13 • unused_field
   info • Avoid `print` calls in production code • lib/src/services/exceptions/server/server_exceptions.dart:58:5 • avoid_print

2022-01-19 08:49 UTC, artem-zaitsev requested changes

2022-01-19 08:49 UTC, artem-zaitsev commented on lib/src/modules/auth/models/request/auth_via_social_model.dart
> +  final String? token;
он по смыслу не может быть null, на данный момент лучше передать сюда при создании пустую строку и оставить туду.

2022-01-19 08:49 UTC, artem-zaitsev commented on lib/src/modules/auth/models/request/register.dart
> +  DateTime? birthDate;
Также - эти параметры не опциональны в запросе.

2022-01-19 08:49 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +  DateTime? birthDate;
Эти поля тебе не имеет смысла хранить. У тебя они приходят в event'е и ты их сразу перенаправляешь на сервер.
Номер телефона мы храним, так как он будет использоваться в нескольких сценариях.

2022-01-19 08:49 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +  AuthBloc(this._repository) : super(LoadingState()) {
У тебя сейчас висит комментарий о том, что этот метод слишком длинный.
Это верно, сейчас уже он начинает замусориваться. Как быть?

По сути вынести анонимные функции, которые ты сейчас создаешь в аргументах on(), в отдельные методы внутри класса. Например:
```
// для SmsAuthEvent
// в конструкторе 
on<SmsAuthEvent>(_handleSmsAuth);

//отдельный метод
void _handleSmsAuth(SmsAuthEvent event, Emitter emit) {
      emit(LoadingState());
      //TODO: нет запроса по авторизации по смс
      // await _repository.
      emit(SuccessState());
}

```

2022-01-19 08:49 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +  AuthBloc(this._repository) : super(LoadingState()) {
Метод сильно сократиться и не будет предупреждения.

2022-01-21 18:42 UTC, MirkoZorich commented
Вынес методы из конструктора.
Убрал лишние переменные.
Токен прилетает из события по этому переменную токен также убрал.

2022-01-21 19:06 UTC, artem-zaitsev requested changes
Небольшие правки, в остальном все неплохо, но обрати внимание на замечания анализатора.

2022-01-21 19:06 UTC, artem-zaitsev commented on lib/src/modules/auth/models/request/auth_via_social_model.dart
> +  final String? token;
не исправлено

2022-01-21 19:06 UTC, artem-zaitsev commented on lib/src/modules/auth/services/events/auth_event.dart
> +}
вообще PhoneAuth == SmsAuth, так как мы отправим в блок СМС, и дальше обратимя в файербейз и потом сразу же отправим запрос на сервер.

2022-01-21 19:06 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +    emit(SuccessState());
Здесь будет то, что сейчас происходит в _handlePhoneAuth, плюс туду, что надо дождаться ответа от файербейз сервиса.

2022-01-23 14:40 UTC, MirkoZorich commented
Чек не проходит из-за не используемого параметра event в _handleLogout, остальные замечания устранил

2022-01-23 17:42 UTC, artem-zaitsev requested changes
Надо еще чуть-чуть привести в порядок

2022-01-23 17:42 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +        phone = event.phone,);
здесь поехало форматирование

2022-01-23 17:42 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +  void _handleSendPhone(event, emit) async {
Не обратил внимания сразу - не используй dynamic в аргументах.

В данном случае тебе каждый метод надо:
- event типизировать типом необходимого Event
- emit -  поставить тип Emitter

2022-01-23 17:42 UTC, artem-zaitsev commented on lib/src/modules/auth/services/auth_bloc.dart
> +  void _handleSendPhone(event, emit) async {
Актуально для всех методов

2022-01-23 19:29 UTC, MirkoZorich commented
Типизировал параметры

2022-01-25 07:30 UTC, merged