Сторедж для токена и рефреш токена
boostgrade/wtgt_beta pull request #34
Opened 2022-02-10 07:08 UTC by Akrid782

[# Ссылка на задачу](https://github.com/boostgrade/wtgt_beta/issues/21)
Задача #21 

# Что было сделано

1. В файле main.dart проинициализирован hive и зарегистрирован адаптер хранилище токена.
2. Добавлены пакеты hive: ^2.0.5, hive_flutter: ^1.1.0 и hive_generator: ^1.1.1
3. Создан класс token_storage по пути lib\src\modules\auth\storage\token_storage.dart и генирован адаптер TokenStorageAdapter в файле token_storage.g.dart 

# Как проверить работу?

Воспользоваться методами управления хранилищем 
Например:
final box = Hive.box<TokenStorage>('tokenBox');

box.add(token);
final tokenStorage= box.getAt(0);
tokenStorage.token= 'что-то';
tokenStorage.save();
box.deleteAt(0);

# Чек-лист

- [Х] Функциональность протестирована и работает корректно
- [ ] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2022-02-10 08:06 UTC, artem-zaitsev commented on lib/main.dart
> +  Hive.registerAdapter(TokenStorageAdapter());
сделай, пожалуйста, глобальную функцию с названием initHive и здесь ее вызови(а в ней эти две строки)

2022-02-10 08:22 UTC, Akrid782 commented on lib/main.dart
> +  Hive.registerAdapter(TokenStorageAdapter());
Исправил

2022-02-10 18:45 UTC, artem-zaitsev requested changes

2022-02-10 18:45 UTC, artem-zaitsev commented on lib/main.dart
> +  iniHive();
await поставь

2022-02-10 18:45 UTC, artem-zaitsev requested changes

2022-02-10 18:45 UTC, artem-zaitsev commented on lib/global_function.dart
> +void iniHive() async {
а здесь Future<void>

2022-02-10 18:54 UTC, Akrid782 commented on lib/main.dart
> +  iniHive();
Исправил

2022-02-11 15:18 UTC, artem-zaitsev approved these changes

2022-02-11 15:20 UTC, merged